name: Periodic GET

on:
  schedule: 
    - cron: '*/14 * * * *'
  workflow_dispatch:

jobs:
  http-request:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        run: nohup curl "https://si-activities-api.onrender.com/api/activities" > /dev/null2>&1 &
